@hostname = http://localhost:8000
@api_prefix = /api


### Ver Lista Completa de Descalificados
GET {{hostname}}{{api_prefix}}/descalificados
Accept: application/json

/*
HTTP/1.1 200 OK
Content-Type: application/json

{
  "message": "Lista consolidada de descalificados.",
  "cantidad": 1,
  "data": [
    {
      "tipo": "ETICA_EXAMEN",
      "id_competidor": 45,
      "nombre_completo": "Juan Perez",
      "ci": "1234567",
      "institucion": "Colegio San Calixto",
      "motivo": "Sanción: Incumplimiento de reglas",
      "fecha": "2023-10-27T15:30:00.000000Z",
      "examen_afectado": "Examen Final Matemáticas"
    }
  ]
}
*/

### Descalificar un competidor administrativamente (POST)
POST {{hostname}}{{api_prefix}}/descalificados
Content-Type: application/json
Accept: application/json

{
  "id_competidor": 1,
  "observaciones": "Incumplimiento grave del reglamento del evento. Se encontraron materiales no autorizados."
}

/*
HTTP/1.1 201 Created
Content-Type: application/json

{
    "message": "Competidor descalificado administrativamente con éxito.",
    "data": {
        "id_competidor": "1",
        "observaciones": "Incumplimiento grave del reglamento del evento. Se encontraron materiales no autorizados.",
        "id_descalificacion": 1
    }
}
*/